#!/usr/bin/env bash
set -Eeuo pipefail # https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/#:~:text=set%20%2Du,is%20often%20highly%20desirable%20behavior.

# enable the line below for debugging information
# set -xv

# on macOS 11.5+, pls run "brew install coretools" to install realpath
DATADIR=$(realpath "$1")
CONTAINER_NAME="postgres-${DATADIR//[^a-zA-Z0-9_.-]/_}"
#IMAGE='postgres:latest'
# using fixed image, to prevent breaking due to upgraded image versions
IMAGE='postgres:12.8-buster'
COMMAND=''
if [ -n "${2-}" ]; then
    COMMAND="-c \"$2\""
fi

if [ -t 0 ]; then
    # used interactively
    INTERACTIVE="-it"
else
    # got stdin
    INTERACTIVE="-i"
fi

POSTGRES_OPTS=""
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'max_connections=200'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'shared_buffers=4GB'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'effective_cache_size=12GB'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'maintenance_work_mem=1GB'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'checkpoint_completion_target=0.7'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'wal_buffers=16MB'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'default_statistics_target=100'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'random_page_cost=1.1'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'effective_io_concurrency=200'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'work_mem=1GB'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'min_wal_size=1GB'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'max_wal_size=2GB'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'max_worker_processes=8'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'max_parallel_workers_per_gather=8'"
POSTGRES_OPTS="${POSTGRES_OPTS} -c 'max_parallel_workers=8'"

mkdir -p "$DATADIR"
docker run --rm \
    "$INTERACTIVE" \
    --name "$CONTAINER_NAME" \
    -v "$DATADIR":/var/lib/postgresql/data \
    -e POSTGRES_PASSWORD=mysecretpassword \
    --user $UID \
    --shm-size=8g \
    "$IMAGE" \
    bash -c "(/usr/local/bin/docker-entrypoint.sh postgres $POSTGRES_OPTS &) &>/dev/null; until pg_isready -U postgres &>/dev/null; do sleep 0.1; done; psql -U postgres -d postgres --echo-all -v ON_ERROR_STOP=1 $COMMAND; EXIT_CODE=\$?; pg_ctl stop &>/dev/null; exit \$EXIT_CODE"

